FROM langflowai/langflow:latest

COPY requirements.txt /tmp/requirements.txt

RUN uv pip install -r /tmp/requirements.txt

CMD ["langflow", "run", "--env-file", "/app/.env", "--host", "0.0.0.0", "--port", "7860"]