services:
  langflow:
    build:
      context: .
      dockerfile: Dockerfile-langflow
    container_name: langflow
    user: "0:0"
    ports:
      - "7860:7860"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # ИСПОЛЬЗУЕМ СВОЮ БАЗУ
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow_db
      - LANGFLOW_CONFIG_DIR=/app/langflow
      - LANGFLOW_SAVE_DB_IN_CONFIG_DIR=true
      - LANGFLOW_SKIP_AUTH_AUTO_LOGIN=true

      # Langfuse
      - LANGFUSE_SECRET_KEY=sk-lf-11cc03cb-e4fb-4a75-a89c-bda7229c909c
      - LANGFUSE_PUBLIC_KEY=pk-lf-5668670b-8e89-406e-81fa-2f5c8f65005d
      - LANGFUSE_HOST=https://cloud.langfuse.com
    volumes:
      - langflow_data:/app/langflow
      - ./custom_components:/app/custom_components
    networks:
      - langflow-network
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: langflow-postgres
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      # Это создаст базу по умолчанию, но скрипт ниже создаст остальные
      POSTGRES_DB: langflow_db
    ports:
      - "5433:5432"
#    command: >
#      sh -c "echo 'CREATE DATABASE litellm_db;' > /docker-entrypoint-initdb.d/init.sql && docker-entrypoint.sh postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - langflow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langflow -d langflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5

#  litellm:
#    image: ghcr.io/berriai/litellm:main-latest
#    container_name: litellm
#    ports:
#      - "4000:4000"
#    volumes:
#      - ./litellm-config.yaml:/app/config.yaml
#    environment:
#      # ИСПОЛЬЗУЕМ СВОЮ ОТДЕЛЬНУЮ БАЗУ
#      - DATABASE_URL=postgresql://langflow:langflow@postgres:5432/litellm_db
#      - GIGACHAT_CREDENTIALS=MDE5YTk2YWQtMTUyNi03ODQxLWJmN2ItODI0Njc5YTBjZDM0OmRmZDQ0YmEzLWJiYjUtNGIwMy04YzJlLTZlOWM2YzUzMDdiNg==
#      - GIGACHAT_SCOPE=GIGACHAT_API_PERS
#    command: [ "--config", "/app/config.yaml" ]
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - langflow-network
#    restart: unless-stopped

volumes:
  langflow_data:
  postgres_data:

networks:
  langflow-network:
    driver: bridge
    name: langflow-network